#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/env-local.php';
require __DIR__ . '/env.php';

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/ziiframework/zii/src/Yii.php';

$ztmp_config = yii\helpers\ArrayHelper::merge(
  require __DIR__ . '/config/base.php',
  require __DIR__ . '/config/base-local.php',
  require __DIR__ . '/config/cli.php'
);

unset($ztmp_config['class']);

exit((new yii\console\Application($ztmp_config))->run());
